name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: chat.sln 
   
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Publish
      run: dotnet publish ChatApp -c Release -r win-x64 -o outChatApp

    - name: Publish
      run: dotnet publish ChatAppClient -c Release -r win-x64 -o outChatAppClient

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ChatApp
        path: ./out/ChatApp

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ChatAppClient
        path: ./out/ChatAppClient

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: ./out/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}